name: Release & Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org/'

      - name: Install UglifyJS
        run: npm install -g uglify-js

      - name: Minify tree.js
        run: uglifyjs tree.js -o tree.min.js --comments

      - name: Publish to npm
        if: env.NPM_TOKEN != ''
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            tree.js
            tree.min.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 